version: "3.9"

services:
  postgres:
    container_name: "postgres"
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: "redis"
    env_file:
      - .env
    image: redis:7.0-alpine
    restart: always
    entrypoint: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASS} --loglevel warning
    ports:
      - "${REDIS_PORT}:6379"

  uvicorn:
    container_name: "uvicorn-fastapi"
    build: .
    depends_on:
      - postgres
      - redis
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app

  nettools:
    container_name: "nettools"
    image: wbitt/network-multitool:fedora-minimal

volumes:
  postgres:
    driver: local
  app:
