"""Created

Revision ID: 6b546c3e845e
Revises: 
Create Date: 2023-05-29 10:22:21.354703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b546c3e845e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_type',
    sa.Column('code', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('word_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_distribution_type_code'), 'distribution_type', ['code'], unique=False)
    op.create_table('language',
    sa.Column('code', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('is_ui_lang', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_language_code'), 'language', ['code'], unique=False)
    op.create_table('type',
    sa.Column('code', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('word_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_type_code'), 'type', ['code'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('credential', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_code', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['lang_code'], ['language.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_word_code'), 'dictionary', ['word_code'], unique=False)
    op.create_table('theme',
    sa.Column('code', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('word_code', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_code'], ['type.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_theme_code'), 'theme', ['code'], unique=False)
    op.create_table('tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('type_code', sa.Integer(), nullable=False),
    sa.Column('theme_code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('lang_code', sa.Integer(), nullable=False),
    sa.Column('source_link', sa.String(length=256), nullable=False),
    sa.Column('dist_type_code', sa.Integer(), nullable=False),
    sa.Column('who_added_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dist_type_code'], ['distribution_type.code'], ),
    sa.ForeignKeyConstraint(['lang_code'], ['language.code'], ),
    sa.ForeignKeyConstraint(['theme_code'], ['theme.code'], ),
    sa.ForeignKeyConstraint(['type_code'], ['type.code'], ),
    sa.ForeignKeyConstraint(['who_added_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutorial_id'), 'tutorial', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutorial_id'), table_name='tutorial')
    op.drop_table('tutorial')
    op.drop_index(op.f('ix_theme_code'), table_name='theme')
    op.drop_table('theme')
    op.drop_index(op.f('ix_dictionary_word_code'), table_name='dictionary')
    op.drop_table('dictionary')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_type_code'), table_name='type')
    op.drop_table('type')
    op.drop_index(op.f('ix_language_code'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_distribution_type_code'), table_name='distribution_type')
    op.drop_table('distribution_type')
    # ### end Alembic commands ###
